#ifndef SYSTEM_SETTINGS_H
#define SYSTEM_SETTINGS_H

#include "driver/gpio.h"
#include "driver/i2c.h"

#define SYSTEM_SETTINGS_WIFI_SSID "Please"
#define SYSTEM_SETTINGS_WIFI_PASS "ChangeMe"
#define SYSTEM_SETTINGS_MAX_RETRIES 10

#define SYSTEM_SETTINGS_I2C_SDA_PIN GPIO_NUM_47
#define SYSTEM_SETTINGS_I2C_SCL_PIN GPIO_NUM_21
#define SYSTEM_SETTINGS_I2C_PORT I2C_NUM_0
#define SYSTEM_SETTINGS_I2C_FREQ_HZ 400000

#define SYSTEM_SETTINGS_INTERRUPT GPIO_NUM_1

#define SYSTEM_SETTINGS_UDP_IP   "192.168.1.3"
#define SYSTEM_SETTINGS_UDP_PORT 12345

#endif // WIFI_SETTINGS_H
